# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN dotnet tool install --global dotnet-ef --version 8.*

ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /src

# Copy project file first for better Docker layer caching
COPY GymTracker.csproj ./

RUN dotnet restore

# Copy the remaining source code
COPY . .

# Default command
ENTRYPOINT ["dotnet", "ef", "database", "update"]